name: Rust

on:
  push:
    branches: [ master, test-git-workflow ]
  pull_request:
    branches: [ master, test-git-workfow ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  clippy:
  
    runs-on: ubuntu-latest
  
    steps:
    - name: rust-clippy-check
      # You may pin to the exact commit or the version.
      # uses: actions-rs/clippy-check@b5b5f21f4797c02da247df37026fcd0a5024aa4d
      uses: actions-rs/clippy-check@v1.0.7
      with:
        # GitHub token
        token: ${{ secrets.GITHUB_TOKEN }}
        # Toolchain to use (without the `+` sign, ex. `nightly`)
        # toolchain: # optional
        # Arguments for the cargo command
        args: --all-features
        # Use cross instead of cargo
        use-cross: false
        # Display name of the created GitHub check. Must be unique across several actions-rs/clippy-check invocations.
        name: clippy
