name: Rust

on:
  push:
    branches: [ master, test-git-workflow ]
  pull_request:
    branches: [ master, test-git-workfow ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
